name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:      
        - run: echo "Descargando código"
        - run: echo "Compilando"
        - run: echo "Ejecutando pruebas"
        - run: echo "Todo OK"